[tool.poetry]
name = "time-date-api"
version = "0.1.0"
description = ""
authors = ["Sas2k <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.2"
pytz = "^2021.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
